apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplepython 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplepython
  template:
    metadata:
      labels:
        app: samplepython 
    spec:
      containers:
        - name: samplepython 
          image: demotest09.azurecr.io/samplepython
          ports:
          - containerPort: 5000